name: TabPac
version: '${version}'

main: pac.chromium.TabPac.TabPac
api-version: '1.21.1'
load: POSTWORLD
depend: [PlaceholderAPI]

commands:
  tabpac:
    description: Main command for TabPac
    aliases: [tpac]
    permission: tabpac.use

permissions:
  tabpac.use:
    description: Allows use of /tabpac
    default: true
  tabpac.reload:
    description: Allows reloading the plugin
    default: op
  tabpac.admin:
    description: Allows administrative TabPac actions and notifications
    default: op

authors: [ PacHub228 ]
